ihub/duties/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import (
    duty_api_start_view, duty_api_detail_view,
    duty_template_view
)

app_name = 'duties'

page_urlpath = [
    path('page/', duty_template_view, name='duty-page'),
]

api_urlpath = [
    path('create/', duty_api_start_view, name='duty-create'),
    path('details/', duty_api_detail_view, name='duty-details'),
]

urlpatterns = [
    path('', include(page_urlpath)),
    path('api/', include(api_urlpath)),
]

ihub/ihub/urls.py
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import path, include

from users.views import redirect_login

urlpatterns = [
    path('admin/', admin.site.urls),
    # users login, signup, logout, and page
    path('', redirect_login),
    path('logout', LogoutView.as_view(next_page='/'), name='logout'),
    path('accounts/', include('users.urls')),
    # duties start and details
    path('duties/', include('duties.urls')),
]

ihub/users/urls.py
from django.urls import path, include
from django.contrib.auth.views import LoginView
from .views import HomeView, signup

app_name = 'users'

urlpatterns = [
    path('profile/', HomeView.as_view(), name='home'),
    path('signup/', signup, name='signup'),
    path('login/', LoginView.as_view(
            template_name='login.html', 
            redirect_authenticated_user=True), 
        name='login'),
]

ihub/templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
                <div class="alert alert-danger">
                        <strong>{{ error|escape }}</strong>
                </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
            </div>
    {% endfor %}
{% endif %}

ihub/templates/getstarted.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>iHub · Bootstrap</title>
    <link rel="canonical" href="https://getbootstrap.com/docs/4.3/examples/navbar-static/">

    {% load static %}
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom Style CSS -->
    <style>
        body {
            min-height: 60rem;
    	  }

        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>
</head>
<body>
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <a class="navbar-brand" href="{% url 'users:home' %}">iHubDepot</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'duties:duty-page' %}">Duty</a>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="#">Support</a>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="#">Community</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Accounts</a>
                <div class="dropdown-menu" aria-labelledby="dropdown01">
                    <a class="dropdown-item" href="{% url 'logout' %}">Switch account</a>
                </div>
            </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
</nav>

<div id="dutyModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="exampleModalLabel">Before you started,</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <!-- I'm Subtituting -->
        <h5>I'm Subtituting...</h5>
        <p>If you're subtituting someone in his/her duty, please specify the matric no. of your friend. We will clock this time on behalf of your friend instead of you.
          Read here if you want to know more about <a href="#" class="tooltip-test" title="README">Subtituting on Other's Duty</a> or 
          <a href="#" class="tooltip-test" title="+65 82467547">contact Ms.Clara</a>.
        </p>
        <h6>Enter your friend's matric number:</h6>
        <form>
          <div class="form-row align-items-center">
            <div class="col-sm-4 my-1">
              <label class="sr-only" for="inlineFormInputName">Name</label>
              <input type="text" class="form-control" name="matric" placeholder="Friend's Matric Number" maxlength="10">
            </div>
            <!-- <div class="col-auto my-1">
              <button type="submit" class="btn btn-primary">Submit</button>
            </div> -->
          </div>
        </form>
        <hr>
        <!-- I'm me -->
        <h5>I'm on My Own Duty!</h5>
        <p>If you're not subtituting anybody and you come for your own duty, just go ahead and ignore the above detail. We will get your duty recorded for your payment.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" id="startduty" class="btn btn-primary">Start now</button>
      </div>
    </div>
  </div>
</div>

<!-- Begin page content -->
<main role="main" class="flex-shrink-0">
  <div class="container">
    <h1 class="display-4">Get Started with iHub Web Platform</h1>
    <hr class="my-4">
    <p class="lead">Start your EEE day in our <code>iHub</code>. Ping a friend to study with you or bring your favorite headset to enter your <code>hermit mode;</code> 
      Whether it's a <code>&lt;code_marathon&gt;</code> day or a peaceful study, personalise your space at <code>iHub</code></p>
    <p>Back to <a href="#">iHub student homepage</a> or proceed as iHub guardian here:</p>
  </div>
</main>

<main role="main" class="container">
  <div class="jumbotron js-signin-modal-trigger">
		<h1 class="display-4">Ready Player One...</h1>
		<hr class="my-4">
    <p class="lead">This is a portal to iHub duty session. If you're registered as <a href="#">iHub guardian</a> for this semester, you're welcomed to proceed.
      The duty session will be 3 hours by default. Ready??
    </p>
    <button type="button" class="btn btn-lg btn-primary" data-toggle="modal" data-target="#dutyModal" role="button">Ready launch duty &raquo;</button>
  </div>
</main>

<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<script>
// ajaxSetup
function csrfSafeMethod(method) {
    // these HTTP methods do not require CSRF protection
    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
}
$.ajaxSetup({
    beforeSend: function(xhr, settings) {
        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
            xhr.setRequestHeader("X-CSRFToken", csrftoken);
        }
    }
});

$(function(){
	// function startduty onclick
	$('#startduty').click(function(){
        var matric_val = $("input[name='matric']").val();
        var _data = {}
        // check if matric is filled
        if (matric_val != ''){
            _data = {
                debtee: {
                    matric: matric_val
                }
            };
        }
		$.ajax({
			type: "POST",
			contentType: 'application/json; charset=utf-8',
			url: "{% url 'duties:duty-create' %}",
			data: JSON.stringify(_data),
			dataType: 'json',
			success: function(data){
        // redirect to active duty page
        location.href = "{% url 'duties:duty-page' %}";
			},
			error: function(xhr, status, error){
				var errorMessage = xhr.status + ': ' + xhr.statusText
        // log error
        console.log("matric", matric_val);
				console.log(errorMessage);
			}
		});
	});
});

// using jQuery
function getCookie(name) {
    var cookieValue = null;
    if (document.cookie && document.cookie !== '') {
        var cookies = document.cookie.split(';');
        for (var i = 0; i < cookies.length; i++) {
            var cookie = jQuery.trim(cookies[i]);
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) === (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
}

var csrftoken = getCookie('csrftoken');

</script>
</body>
</html>

ihub/templates/home.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>iHub Depot</title>
    
    {% load static %}
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <style>
    body{
        padding-top: 3.5rem;
    }
    .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
      }
    @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
    }
    </style>

</head>
<body>
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <a class="navbar-brand" href="{% url 'users:home' %}">iHubDepot</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'users:home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'duties:duty-page' %}">Duty</a>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="#">Support</a>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="#">Community</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Accounts</a>
                <div class="dropdown-menu" aria-labelledby="dropdown01">
                    <a class="dropdown-item" href="{% url 'logout' %}">Switch account</a>
                </div>
            </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
</nav>

<main role="main">

<!-- Main jumbotron -->
<div class="jumbotron">
    <div class="container">
        <h1 class="display-3">Hello, {{object.name}}!</h1>
        <p>This is an alpha version of iHub web platform for iHub users and student assistant. It integrates real support for maintaining iHub a convenient place to work and study. May your day start with a smile :)</p>
        <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more &raquo;</a></p>
    </div>
</div>

<div class="container">
    <!-- Cards -->
    <div class="row">
        <div class="col-md-4">
            <h2>Duty</h2>
            <p>Jumpy start your duty as the guardian of iHub. Help maintain peace in iHub using our new platform for fellow students and staffs for the greater good. Signup now and become the hero of our school!</p>
            <p><a class="btn btn-secondary" href="{% url 'duties:duty-page' %}" role="button">View details &raquo;</a></p>
        </div>
        <div class="col-md-4">
            <h2>Support</h2>
            <p>Maintaining iHub is not easy sometimes, but you can help us by real time fault reporting and stay vigilant to your surrounding. We provide 12/7 support for hardware fault and lost of a belonging. </p>
            <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
        </div>
        <div class="col-md-4">
            <h2>Community</h2>
            <p>You're not alone in your duty. In case of emergency and unavailability, we're still here to back you up. Ask a trusty friend in community of iHub guardian to replace you for a day.</p>
            <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
        </div>
        </div>

        <hr>

    </div> <!-- /container -->

</main>

<footer class="container">
<p>&copy; DK 2019-2020</p>
</footer>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="/docs/4.2/assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

</body>
</html>

ihub/templates/login.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="MAIN_HTML">
    <title>Login</title>

    {% load static %}
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{% static 'css/float.css' %}" rel="stylesheet">
  </head>

  <body>
	{% load widget_tweaks %}
    <form class="form-signin" method="post">

		{% csrf_token %}

		<div class="text-center mb-4">
			<img class="mb-4" src="{% static 'assets/bootstrap-solid.svg' %}" alt="" width="72" height="72">

			<h1 class="h3 mb-3 font-weight-normal">Floating labels</h1>
			<!-- <p>Build form controls with floating labels via the <code>:placeholder-shown</code> pseudo-element. <a href="https://caniuse.com/#feat=css-placeholder-shown">Works in latest Chrome, Safari, and Firefox.</a></p> -->
		</div>

		{% include 'form_errors.html' %}

		<div class="form-label-group">
			{% render_field form.username class+="form-control" id="inputEmail" type="email" placeholder="NTU Email Account" %}
			<!-- <input type="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus> -->
			<label for="inputEmail">Email address</label>
		</div>

		<div class="form-label-group">
			{% render_field form.password class+="form-control" id="inputPassword" type="password" placeholder="password" %}
			<!-- <input type="password" id="inputPassword" class="form-control" placeholder="Password" required> -->
			<label for="inputPassword">Password</label>
		</div>

		<div class="checkbox mb-3">
			<label>
			<input type="checkbox" value="remember-me"> Remember me
			</label>
		</div>

		<button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
		<p class="mt-5 mb-3 text-muted text-center">AY 2019/20</p>

</form>
</body>
</html>

ihub/templates/onduty.html
</html>
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

    <title>Active Duty</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/navbar-static/">

	{% load static %}
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom Style CSS -->
    <style>
      body {
        min-height: 60rem;
    	}

      .completion{
        display: none
      }

      .bd-placeholder-img {
          font-size: 1.125rem;
          text-anchor: middle;
          -webkit-user-select: none;
          -moz-user-select: none;
          -ms-user-select: none;
          user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
            font-size: 3.5rem;
        }
      }
    </style>
  </head>

  <body>

    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
      <a class="navbar-brand" href="#">Top navbar</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#">Disabled</a>
          </li>
        </ul>
        <form class="form-inline mt-2 mt-md-0">
          <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>

    <main role="main" class="container">
      <div class="jumbotron">
        <h1 class="display-3">Active CountDown</h1>
        <p class="lead timer-display">Hi</p>
      </div>
      
      <!-- Active Task 1 -->
      <div id="task-active-7558" class="my-3 p-3 bg-white rounded shadow-sm">
        <h6 class="border-bottom border-gray pb-2 mb-0">Task: Act of Conscent</h6>
        <small class="text-left mt-3">
          Status: Pending
        </small>
        <div class="card text-center collapse show" style="border:none">
          <div class="card-body">
            <h5 class="card-title">Special title treatment</h5>
              <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
              <a class="btn btn-outline-primary submitTaskBtn" href="">I Agree</a>
              <a href="" class="btn btn-outline-secondary">Read Policy</a>
          </div>
        </div>
          <small class="d-block text-right mt-3">
              <a href="" class="collapseBtn">Collapse >></a>
          </small>
      </div>

      <!-- Complete Task 1 -->
      <div id="task-completed-7558" class="completion my-3 p-3 bg-white rounded shadow-sm">
        <h6 class="border-bottom border-gray pb-2 mb-0">Task: Act of Conscent</h6>
        <small class="text-left mt-3 text-success">
          Status: Completed
        </small>
        <div class="card text-center collapse show" style="border:none">
          <div class="card-body">
            <h5 class="card-title">Task completed</h5>
            <p class="card-text">This section has been completed by user <i class="far fa-check-circle text-success"></i></p>
          </div>
        </div>
          <small class="d-block text-right mt-3">
          <a href="" class="collapseBtn">Collapse >></a>
        </small>
      </div>

      <!-- Active Task 2 -->
      <div id="task-active-7560" class="my-3 p-3 bg-white rounded shadow-sm">
        <h6 class="border-bottom border-gray pb-2 mb-0">Task: Duty Report</h6>
        <small class="text-left mt-3">
          Status: Pending
          <br><br>
        </small>
        <div class="card collapse show" style="border:none">
          <form>
            <div class="form-group row">
            <div class="col-sm-3">I have ensured the following:</div>
              <div class="col-sm-6">
              <div class="form-check">
                <input class="form-check-input" type="checkbox" id="gridCheck1">
                <label class="form-check-label" for="gridCheck1">
                  Sign in and out my attendance
                </label>
              </div>
              <div class="form-check">
                <input class="form-check-input" type="checkbox" id="gridCheck1">
                <label class="form-check-label" for="gridCheck1">
                  Be present in i-Hub during the tour of duty
                </label>
              </div>
              <div class="form-check">
                <input class="form-check-input" type="checkbox" id="gridCheck1">
                <label class="form-check-label" for="gridCheck1">
                  Shut down PC properly after closing (11:00 pm)
                </label>
              </div>
              <div class="form-check">
                <input class="form-check-input" type="checkbox" id="gridCheck1">
                <label class="form-check-label" for="gridCheck1">
                    Ensure all keyboards , mouse, and chairs all orderly arranged before closure
                </label>
              </div>
              <div class="form-check">
                <input class="form-check-input" type="checkbox" id="gridCheck1">
                <label class="form-check-label" for="gridCheck1">
                  Record left items found in record book
                </label>
              </div>
              <div class="form-check">
                <input class="form-check-input" type="checkbox" id="gridCheck1">
                <label class="form-check-label" for="gridCheck1">
                  Report any happening that needs the attention of staff <br> (Thomas: 96797237)
                </label>
              </div>
              <div class="form-check">
                <input class="form-check-input" type="checkbox" id="gridCheck1">
                <label class="form-check-label" for="gridCheck1">
                  Switch off all lightings before leaving; Ensure the two doors are electronically secured
                </label>
              </div>
            </div>
            </div><br>
            <div class="form-group row">
              <div class="text-center col-sm-11">
              <button type="submit" class="btn btn-outline-primary submitTaskBtn">I acknowledge</button>
              </div>
            </div>
          </form>
        </div>
          <small class="d-block text-right mt-3">
          <a href="" class="collapseBtn">Collapse >></a>
        </small>
      </div>

      <!-- Complete Task 2 -->
      <div id="task-completed-7560" class="completion my-3 p-3 bg-white rounded shadow-sm">
        <h6 class="border-bottom border-gray pb-2 mb-0">Tasks: Duty Report</h6>
        <small class="text-left mt-3 text-success">
          Status: Completed
        </small>
        <div class="card text-center collapse show" style="border:none">
          <div class="card-body">
            <h5 class="card-title">Task completed</h5>
            <p class="card-text">This section has been completed by user <i class="far fa-check-circle text-success"></i></p>
          </div>
        </div>
        <small class="d-block text-right mt-3">
          <a class="collapseBtn" href="">Collapse >></a>
        </small>
      </div>
    </main>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'js/internal/clock.js' %}"></script>
<script src="{% static 'js/internal/cards.js' %}"></script>
<!-- AJAX Request -->
<script>

function getDuty(){
  $.ajax({
    type: "GET",
    contentType: 'application/json',
    url: "{% url 'duties:duty-details' %}",
    dataType: 'json',
    success: function(data){
      console.log(data)
      const serverNow = data.now;
      const duty_end = data.payload[0].duty_end;
      dutyClock(serverNow, duty_end);
    },
    error: function(xhr, status, error){
      var errorMessage = xhr.status + ': ' + xhr.statusText
      // log error
      console.log("matric", matric_val);
      console.log(errorMessage);
    }
  });
}

getDuty();
</script>

<!-- Task Card Elements -->
<script>
const task1 = {active: "#task-active-7558", completed:"#task-completed-7558"};
const task2 = {active: "#task-active-7560", completed:"#task-completed-7560"};
handleTaskCardsDisplay([task1, task2]);
</script>

</body>
</html>

ihub/templates/signup.html
<h1>Sign up</h1>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Sign up</button>
</form>